#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=iiop miop FT ziop

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=hg

include $(DIRMAKE)/make.rules 

DES_HDRS=$(TIDORBC_PATH)/include/TIDorb/core/comm

include $(DIRMAKE)/$(TIPO_NIVEL).make



