


/********************************************************************************

		CORBA 3.0 Fault Tolerant CORBA - Transport Heartbeats

*********************************************************************************/
#ifndef _FT_IDL_
#define _FT_IDL_

#include "orb.idl"
#include "TimeBase.idl"

#pragma prefix "omg.org"

module FT {

  const CORBA::PolicyType HEARTBEAT_POLICY         = 48;
  const CORBA::PolicyType HEARTBEAT_ENABLED_POLICY = 49;

  struct HeartbeatPolicyValue {
    boolean heartbeat;
    TimeBase::TimeT heartbeat_interval;
    TimeBase::TimeT heartbeat_timeout;
  };

  local interface HeartbeatPolicy : CORBA::Policy {
    readonly attribute HeartbeatPolicyValue heartbeat_policy_value;
  };

  local interface HeartbeatEnabledPolicy : CORBA::Policy {
    readonly attribute boolean heartbeat_enabled_policy_value;
  };

};

#endif // _FT_IDL_

