#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=01_orb 02_comm 03_sending_context 04_bidir_policy 05_cos_naming 06_dynamic_any 07_TimeBase 08_FT 09_PortableGroup 10_Messaging 11_Compression

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=b

include $(DIRMAKE)/make.rules 

LIBNAME=TIDorbIdl

include $(DIRMAKE)/$(TIPO_NIVEL).make



