#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------


#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=hg

include $(DIRMAKE)/make.rules 

DES_HDRS=$(TIDORBC_PATH)/include/TIDorb/core/util/exceptions

include $(DIRMAKE)/$(TIPO_NIVEL).make



