#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------


#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=cp

include $(DIRMAKE)/make.rules 

CP_DESTINO=$(TIDORBC_PATH)/include/TIDorb/core/util

include $(DIRMAKE)/$(TIPO_NIVEL).make



