#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=exceptions
MYDEFINES=-D__STDC_LIMIT_MACROS

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=do

include $(DIRMAKE)/make.rules $(DIRMAKE)/$(TIPO_NIVEL).make
