#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=include IDL TIDorb

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=ss

include $(DIRMAKE)/make.rules $(DIRMAKE)/$(TIPO_NIVEL).make



