#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=include tidsocket

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=b

include $(DIRMAKE)/make.rules $(DIRMAKE)/$(TIPO_NIVEL).make



