#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=templates portable core dynAny types util 

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=b

include $(DIRMAKE)/make.rules $(DIRMAKE)/$(TIPO_NIVEL).make



