#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=cdr comm iop poa goa typecode util messaging compression ziop

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=do

include $(DIRMAKE)/make.rules $(DIRMAKE)/$(TIPO_NIVEL).make



