#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------


#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=hg

include $(DIRMAKE)/make.rules 

DES_HDRS=$(TIDORBC_PATH)/include/TIDorb/dynAny

include $(DIRMAKE)/$(TIPO_NIVEL).make



