#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=policies

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=hg

include $(DIRMAKE)/make.rules 

DES_HDRS=$(TIDORBC_PATH)/include/TIDorb/core/poa

include $(DIRMAKE)/$(TIPO_NIVEL).make



