#----------------------------------------------------------------------
# Cambiar el orden de compilacion
#----------------------------------------------------------------------

MYDIR=cdr comm iop poa goa typecode util messaging compression ziop

#----------------------------------------------------------------------
# Incluir las reglas de compilacion
#---------------------------------------------------------------------

TIPO_NIVEL=hg

include $(DIRMAKE)/make.rules 

DES_HDRS=$(TIDORBC_PATH)/include/TIDorb/core

include $(DIRMAKE)/$(TIPO_NIVEL).make



